### ISSUE TITLE
Error signing on debian stable.

### ISSUE THREAD

**Issue by luisza** [fdelapena/firmador-pdf#1]
I get this error trying to sign on my debian 9 stable.

![firmador_error](https://user-images.githubusercontent.com/7146904/38817573-df8b4a10-4155-11e8-858c-6e95095cbc86.png)

This is my java environment
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Also try con build with maven but error persist.

**Comment by fdelapena** [comment]
It shows a `CKR_GENERAL_ERROR`, it usually happens to me when `pcscd.socket` is not working properly, it gets `pcscd.service` up when needed. Please try restarting them.

**Comment by luisza** [comment]
Oh, this was my fault pcsd server was down, now with service up I get this error when try to sign

![firmador_error](https://user-images.githubusercontent.com/7146904/38819486-c80ce012-4158-11e8-90b9-e265328b2b4e.png)

**Comment by fdelapena** [comment]
Yes, I have this one here too, line 205 does not handle properly arguments, this is a bug. Try running the jar without args in the meanwhile to work around it.

**Comment by luisza** [comment]
Oh, you are right. Thanks.
